/*
 * Copyright (C) 2018 cosmo
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package br.edu.ufersa.valecius.tcc.form.admissivel;

import br.edu.ufersa.valecius.tcc.form.*;
import br.edu.ufersa.valecius.tcc.utils.VariavelCl;
import static java.lang.Math.sqrt;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author cosmo
 */
public class EquacoesProjetoAdmForm extends javax.swing.JFrame {

    /**
     * Creates new form EquacoesProjetoForm
     */
    VariavelCl vci;

    public EquacoesProjetoAdmForm(VariavelCl vc) {
        initComponents();

        vci = vc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jb_aco = new javax.swing.JButton();
        jb_alu = new javax.swing.JButton();
        jb_madeira = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ufersa/valecius/tcc/res/ufersa-icon2.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("EQUAÇÕES DE PROJETO");

        jLabel3.setText("SEELECIONE O MATERIAL DA COLUNA : ");

        jb_aco.setText("AÇO");
        jb_aco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_acoActionPerformed(evt);
            }
        });

        jb_alu.setText("ALUMÍNIO");
        jb_alu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_aluActionPerformed(evt);
            }
        });

        jb_madeira.setText("MADEIRA");
        jb_madeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_madeiraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3)))
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jb_aco)
                        .addGap(43, 43, 43)
                        .addComponent(jb_alu)
                        .addGap(45, 45, 45)
                        .addComponent(jb_madeira)))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_aco)
                    .addComponent(jb_alu)
                    .addComponent(jb_madeira))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_acoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_acoActionPerformed
        // TODO add your handling code here:
        EquacoesProjetoAdmAco equacoesProjetoAdmAco = new EquacoesProjetoAdmAco(vci);
        equacoesProjetoAdmAco.show();
    }//GEN-LAST:event_jb_acoActionPerformed

    private void jb_aluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_aluActionPerformed
        // TODO add your handling code here:
        Double res = null;
        Double I = 0.0;

        Double r = null;

        if (vci.getRx() > vci.getRy()) {
            r = vci.getRy();
        } else if (vci.getRx() <= vci.getRy()) {
            r = vci.getRx();
        }

        try {

            Double y = vci.getLef() / r;
            System.out.println("Valor de Y : " + y);

            if (0 <= y && y <= 12) {
                res = (195 * Math.pow(10, 6));
                System.out.println("1");
            } else if (12 < y && y < 55) {
                res = ((214.5 - 1.628 * y) * Math.pow(10, 6));
                System.out.println("2");
            } else if (y >= 55) {
                res = (378125 * Math.pow(10, 6)) / Math.pow(y, 2);
                System.out.println("Valor Res fora : " + res);
                System.out.println("3");
            }

            vci.setResObj(res);
            System.out.println("Valor res dividido pela Area : " + vci.getResObj());
            System.out.println("Valor Area : " + vci.getA());

            EquacoesProjetoAdmProxAlu equacoesProjetoAdmProxAlu = new EquacoesProjetoAdmProxAlu(vci);
            equacoesProjetoAdmProxAlu.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro !");
        }
    }//GEN-LAST:event_jb_aluActionPerformed

    private void jb_madeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_madeiraActionPerformed

        Exception e = null;
        // TODO add your handling code here:
        System.out.println("Tipo : " + vci.getTipo());
        if (vci.getTipo() != 2 && vci.getTipo() != 1) {
            try {
                throw e;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Não é retangular !");
            }
        }

        try {

            Double res = null;
            Double I = 0.0;

            Double vMe = null;

            if (vci.getB() < vci.getH()) {
                vMe = vci.getB();
            } else if (vci.getB() >= vci.getH()) {
                vMe = vci.getH();
            }

            Double y = vci.getLef() / vMe;

            System.out.println("Valor y : " + y);

            if (0 <= y && y <= 11) {
                res = 8.25 * Math.pow(10, 6) * vci.getA();
                JOptionPane.showMessageDialog(rootPane, "A carga crítica é : " + res);
            } else if (11 < y && y <= 26) {
                res = (8.25 * (1 - (1.0 / 2028.0) * (y * y))) * vci.getA();
                JOptionPane.showMessageDialog(rootPane, "A carga crítica é : " + res);
            } else if (y > 26 && y <= 50) {
                res = (3781 * Math.pow(10, 6) / (y * y)) * vci.getA();
                JOptionPane.showMessageDialog(rootPane, "A carga crítica é : " + res);
            } else if (y > 50) {
                JOptionPane.showMessageDialog(null, "Configuração não catalogada e portanto inviável !");
            }

            
            
            
            res/= vci.getA();
            
            System.out.println("Area : "+vci.getA());
            System.out.println("Res com a divisao : "+res);
            
            vci.setResObj(res);
            
            EquacoesProjetoAdmProxMad equacoesProjetoAdmProxMad = new EquacoesProjetoAdmProxMad(vci);
            equacoesProjetoAdmProxMad.setVisible(true);
            
        } catch (Exception c) {
            JOptionPane.showMessageDialog(null, "Erro !");
        }


    }//GEN-LAST:event_jb_madeiraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EquacoesProjetoAdmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EquacoesProjetoAdmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EquacoesProjetoAdmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EquacoesProjetoAdmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VariavelCl vcc = null;
                new EquacoesProjetoAdmForm(vcc).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jb_aco;
    private javax.swing.JButton jb_alu;
    private javax.swing.JButton jb_madeira;
    // End of variables declaration//GEN-END:variables
}
